name: Build Docker image

on:
  push:
    branches:
      - '*'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: false
