name: Build Docker image

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: false
