name: Docker Build And Push To Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v1
        id: git_checkout

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: appsinet/php_development:1.0.$GITHUB_RUN_NUMBER,appsinet/php_development:latest

      - name: Build Docker Image
        run: docker build -t  . && docker push appsinet/php_development:1.0.$GITHUB_RUN_NUMBER && docker logout
